### PR TITLE
Introduce Typescript for semantic search 

### PR DESCRIPTION
**Pull request by lizozom**
Related to https://github.com/do-me/SemanticFinder/issues/3

 * Move code into an `src` folder
 * TypeScriptify the `semantic` file
 * Extract a `utils.ts` file

@do-me I def understand if you prefer sticking with JS. Let me know and I'll close the PR 🖖🏻

### CODE REVIEW

**Comment by do-me** [comment]
Thanks! As mentioned in #16 pinging @VarunNSrivastava whether you'd be fine with TS too. If yes we can merge, if not I'd prefer not to.

**Comment by lizozom** [comment]
In the meanwhile I'll give `JSDoc` a try. So hold off with merging for now.

My next step is to offload the embedding to a `Worker` and try out multithreading as we discussed here.
Sounds ok?

**Comment by VarunNSrivastava** [comment]
Let me know how JSDoc works. I have no familiarity with TS but happy with learning as I go along. Also, isn't multithreading for serverside code, not possible on browsers? I have no experience here so please correct me

**Comment by lizozom** [comment]
JSDoc is 🔥 
https://github.com/do-me/SemanticFinder/pull/18

Modern browsers support some for of threading using a [Web Worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers). I already have a working example.
I'll benchmark it and make a PR.

**Pull request closed without merging**
