### PR TITLE
PDF detection change

### PR DESCRIPTION
**Pull request by Catmaniscatlord**
I was having some issues with this plugin on websites with pdfs.

This change fixes that by inserting a hook to gather information about the web page

### CODE REVIEW

**Comment by do-me** [comment]
Thanks a lot for this PR! 
Checking for the contentType seems like the best solution. As this requires adding scripting permissions it might take a little longer for the Chrome store to review this release. Once approved, I'll let you know.

**Comment by Catmaniscatlord** [comment]
Cool thanks!

I was having a little bit of pain when it came to formatting the files.
How do you go about formatting the javascript files when you work on this project?

**Comment by do-me** [comment]
Are you speaking just of the extension JS files? In that case @VarunNSrivastava can maybe tell you more about it as he created the extension in the first place. 
What exactly are you referring to? In case you have ideas how to improve it or other best practice guidelines I'm all ears! :)

**Comment by Catmaniscatlord** [comment]
as in what are you using to format the javascript files.

Although speaking of suggestions I think it would be a good idea to set up a key bind, like ctrl+shift+f to open a search bar,
and then display the results on the side of the tab for easier navigation.

**Comment by VarunNSrivastava** [comment]
I don't quite remember the directory structure I used. I used WebStorm to format the individual files themselves. Let me know if you have any specific questions.

Would be happy to make the extension pop up with a key bind, as well as improvements to the PDF search. Would be happy to look at such PRs.

**Pull request merged**
