### PR TITLE
Add extension directory to this folder

### PR DESCRIPTION
**Pull request by VarunNSrivastava**
Updated and improved extension added to this repository. Now using the latest version of transformers.js instead of an unmerged PR.

Todo:
- ui changes
- better error handling 
- some problems selecting certain texts

### CODE REVIEW

**Comment by do-me** [comment]
This is so awesome! Works like a charm, there are no more build errors :) 

I have a few unsorted thoughts I'd like to share:

- I'll change the readme, renew the gifs and share the news! 
- Currently the extension relies on the onnxruntime-web folder from the parent directory. I think it would be better and easier if one wouldn't need to run `npm install` and `npm run build` twice (1x in main dir, 1x in extension folder)
- Do you think we could use localStorage for persisting the indexation for sites where the extension already ran? This would be very convenient, as it would drastically improve the UX for repeated visits. Afaik in `semantic.js` you're already caching the model. Adding `embeddingsDict` to the [localStorage](https://stackoverflow.com/a/2010948/13083583) seems to be fairly easy (even though it might need be stringified and after parsed again). When initially loading the extension, it would check whether such an object already exists. However, that might add further complexity as there should be a feature to force a new indexation. A workaround for this might be just to delete the Local Storage on the site. 
image

- For the common user it might be useful to publish releases in the repo or even better: [publish in Chrome Webstore](https://developer.chrome.com/docs/webstore/publish/). Would you like to do this? If not, I could also take care. Instead of using our clear names, we could also [create a developer account for the repo](https://developer.chrome.com/docs/webstore/publish/#setup-a-developer-account).
- There might even be an option to load the extension [on mobile](https://www.makeuseof.com/chrome-extensions-android-mobile/), but with a different browser 
- It's fairly easy to change the model (just one line [here](https://github.com/do-me/SemanticFinder/blob/main/extension/src/semantic.js#L20)) and rebuild the extension but maybe it might be better to generally switch the defaults, e.g. to a multilingual model as [mentioned here](https://github.com/do-me/SemanticFinder/discussions/32#discussioncomment-6667030)?

**Comment by VarunNSrivastava** [comment]
Thanks for checking it out!

Preferably hold off on sharing the news until we get a few more updates. When we feel ready to release this on the chrome store, after some bugfixing and UI changes, I think [Xenova would probably happily re-share](https://twitter.com/xenovacom/status/1682028241845121026) at that point.

I think it would be really smart to cache embeddings and even page content. I'll look into that and get it up and running. 

At some point we can build an "extension preferences" menu where all those advanced settings (how we split, some model options, etc) are available. 

Unfortunately I don't have android so I'm not likely to attempt developing the mobile version.

**Comment by do-me** [comment]
> Preferably hold off on sharing the news until we get a few more updates.

Agree, it's probably better to mature the plugin a little bit more. 

> Unfortunately I don't have android so I'm not likely to attempt developing the mobile version.

The link I shared above is actually installing the "normal" browser extension developed for desktop use on mobile - so no need to develop anything else!

**Comment by do-me** [comment]
Let's continue the discussion in #15 , that might be a better place.

**Pull request merged**
