### PR TITLE
Use semantic-js package

### PR DESCRIPTION
**Pull request by lizozom**
I extracted a semantic search package 
This is an implementation of the demo using that package.

Note that the progress bar is gone, as the worker returns the final list.

### CODE REVIEW

**Comment by lizozom** [comment]
No problem, I'm pretty sure I could stream the results from the package, instead of returning them in one piece. 

Regardless, I think we should decide whether we want to use a package or not (I will gladly make you guys co-admins @do-me @VarunNSrivastava ), otherwise we're going to get a bunch of conflicts.

**Comment by lizozom** [comment]
And the table is @VarunNSrivastava 's doing!

**Comment by VarunNSrivastava** [comment]
I used [Xenova's demo](https://xenova.github.io/transformers.js/) for reference on how to do progress bars with WebWorkers. Once my PR is merged hopefully the progress bars look a little cleaner and we can implement this in semantic-js.

**Comment by lizozom** [comment]
Replaced with https://github.com/do-me/SemanticFinder/pull/26

**Pull request closed without merging**
